### ISSUE TITLE
Getting patternizer image in python

### ISSUE THREAD

**Issue by sagarwaghmare69** [matthewlein/patternizer.js#3]
Hi Matthew,
I really liked your work with patternizer.
I was wondering if it is possible to call/generate patternizer images as numpy array or PIL images.

Regards,
Sagar M. W

**Comment by matthewlein** [comment]
Hi Sagar, thanks for the support. 

I had to google those terms 😅

As it is now, patternizer is very DOM dependent, using a canvas element. If python has a canvas drawing library, it should be relatively straightforward to translate. The lib essentially just draws rects in a loop, nothing too fancy. any drawing tool could do it in any language. 

Another alternative might be some kind of virtual DOM or headless browser to process it as is but that seems like more work.

**Comment by sagarwaghmare69** [comment]
Hi Matthew,
:)
Thank you for prompt response.
I will try to see if if there is any relevant library for python. 

Thank you.

**Comment by sagarwaghmare69** [comment]
Closing the issue.
